name: Setup CI
on:
  push:
    paths:
      - ".upptimerc.yml"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:
concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}-upptime
  cancel-in-progress: false
jobs:
  release:
    name: Setup Upptime
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ github.token }}
      - name: Update response time
        uses: upptime/uptime-monitor@v1.43.0
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.43.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ github.token }}
      - name: Generate site
        uses: upptime/uptime-monitor@v1.43.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ github.token }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: "site/status-page/__sapper__/export/"
          force_orphan: "false"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
