name: Static Site CI
on:
  push:
    paths:
      - "assets/**"
  schedule:
    - cron: "0 1 * * *"
  repository_dispatch:
    types: [static_site]
  workflow_dispatch:
concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}-upptime
  cancel-in-progress: false
jobs:
  release:
    name: Build and deploy site
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ github.token }}
      - name: Generate site
        uses: upptime/uptime-monitor@v1.43.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ github.token }}
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 6339de71f020c5595953afdd57358f9a
          projectName: dollarbox-status
          directory: site/status-page/__sapper__/export/
          gitHubToken: ${{ github.token }}
