name: Summary CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:
concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}-upptime
  cancel-in-progress: false
jobs:
  release:
    name: Generate README
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ github.token }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.43.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ github.token }}
